{
 "title": "AirForecast  dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Forecast data +5h", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "forecast_data = from(bucket: \"PMS sensor project\")\r\n  |> range(start: -5h)  // Upewnij się, że masz wystarczającą ilość danych historycznych\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"Temperature\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> aggregateWindow(every: 5m, fn: mean)\r\n  |> holtWinters(n: 5, seasonality: 12, interval: 5m)\r\n  |> yield(name: \"Predicted Temperature\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "forecast_data = from(bucket: \"PMS sensor project\")\r\n  |> range(start: -5h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\") \r\n  |> filter(fn: (r) => r._field == \"Humidity\") \r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> aggregateWindow(every: 5m, fn: mean)  \r\n  |> holtWinters(n: 5, seasonality: 12, interval: 5m) \r\n  |> yield(name: \"Predicted Humidity\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "forecast_data = from(bucket: \"PMS sensor project\")\r\n  |> range(start: -5h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\") \r\n  |> filter(fn: (r) => r._field == \"Pressure\") \r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> aggregateWindow(every: 5m, fn: mean)  \r\n  |> holtWinters(n: 5, seasonality: 12, interval: 5m) \r\n  |> yield(name: \"Predicted Pressure\")"
    }
   ]
  },
  {
   "title": "AQI 2.5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "forecast_data = from(bucket: \"PMS sensor project\")\r\n  |> range(start: -5h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\") \r\n  |> filter(fn: (r) => r._field == \"AQI index for PM 25\") \r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> aggregateWindow(every: 5m, fn: mean)  \r\n  |> holtWinters(n: 5, seasonality: 12, interval: 5m) \r\n  |> yield(name: \"Predicted AQI 2.5\")"
    }
   ]
  },
  { "title": "Current data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "AQI index for PM10",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\") |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"AQI index for PM 10\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"AQI_PM10\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "AQI index for PM2.5 ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"AQI index for PM 25\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"AQI_PM25\")\r\n  \r\n"
    }
   ]
  },
  {
   "title": "PM 2.5 µg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"PM 25\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"PM25\")"
    }
   ]
  },
  {
   "title": "PM1 µg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"PM 1\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"PM1\")"
    }
   ]
  },
  {
   "title": "PM10 µg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"PM 10\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"PM10\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "\r\n  from(bucket: \"PMS sensor project\") \r\n  |> range(start: -12h) \r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\" and r._field == \"Pressure\" and r.Device_info == \"ESP32-C3-MINI\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"Temperature\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"Temperature\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"PMS sensor project\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32_weather_station\")\r\n  |> filter(fn: (r) => r._field == \"Humidity\")\r\n  |> filter(fn: (r) => r.Device_info == \"ESP32-C3-MINI\")\r\n  |> yield(name: \"Humidity\")"
    }
   ]
  }
 ]
}